model = "gpt-5.5"
model_reasoning_effort = "high"

[projects."/Users/eyedroot/Github/habitdog"]
trust_level = "trusted"

[projects."/Users/eyedroot/Github/cora-app"]
trust_level = "trusted"

[projects."/Users/eyedroot/Github/cora-sb"]
trust_level = "trusted"

[projects."/Users/eyedroot/Documents/Codex/2026-05-04/hyperframes-plugin-hyperframes-openai-curated"]
trust_level = "trusted"

[projects."/Users/eyedroot/Documents/Codex/2026-05-04/mcp"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.3-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"

[mcp_servers.expo-mcp]
url = "https://mcp.expo.dev/mcp"

[mcp_servers.ref-tools]
url = "https://server.smithery.ai/@ref-tools/ref-tools-mcp/mcp"
enabled = false

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.pencil]
command = "/Applications/Pencil.app/Contents/Resources/app.asar.unpacked/out/mcp-server-darwin-arm64"
args = ["--app", "desktop"]
enabled = false

[mcp_servers.figma-mcp-go]
command = "npx"
args = ["-y", "@vkhanhqui/figma-mcp-go"]

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."hyperframes@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-05-09T02:21:43Z"
source_type = "local"
source = "/Users/eyedroot/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-08T12:14:59Z"
source_type = "local"
source = "/Users/eyedroot/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[hooks.state]

[hooks.state."/Users/eyedroot/Github/cora-app/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:6a989d6a5ac1f31a63e5596c8a1f1a9463d3c0906d1cbf2504bc1dab48de225a"

[hooks.state."/Users/eyedroot/Github/cora-app/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:b9b1b25644e8aff7a048dc65e52cf9847f74978ed79a6fc2ced34575ee5f66a7"

[hooks.state."/Users/eyedroot/Github/cora-app/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:6b71f532d8a3c06b819aca6e9aa73e055e7027d2e033961ea3ed09518bb5bb21"

[hooks.state."/Users/eyedroot/Github/cora-app/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:1995def448458bc13218cab3a54e85b32c58f9b1d692a0d28003472a09d5a7b5"

[tui.model_availability_nux]
"gpt-5.5" = 2

[profiles.auto]
approval_policy = "never"
sandbox_mode = "workspace-write"
