# Brewfile - Homebrew packages for dotfiles
# Usage: brew bundle --file=~/.Brewfile

# Taps
tap "homebrew/bundle"
tap "oven-sh/bun"

# ===== Formulae =====
brew "btop"
brew "oven-sh/bun/bun"
brew "claude-code"
brew "colima"
brew "composer"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "fastfetch"
brew "ffmpeg"
brew "fzf"
brew "starship"
brew "tmux"
brew "zoxide"
brew "gh"
brew "git"
brew "htop"
brew "k9s"
brew "deno"
brew "libpq"
brew "mole"
brew "node"
brew "nvm"
brew "pnpm"
brew "uv"
brew "wget"
brew "yarn"
brew "yt-dlp"

# ===== Casks (GUI Applications) =====
cask "1password-cli"
cask "android-platform-tools"
cask "appcleaner"
cask "betterdisplay"
cask "claude-island"
cask "cloudflare-warp"
cask "codex"
cask "deepl"
cask "figma"
cask "forklift"
cask "ghostty"
cask "herd"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "keyboard-cleaner"
cask "laradumps"
cask "lens"
cask "medis"
cask "mongodb-compass"
cask "orbstack"
cask "path-finder"
cask "ray"
cask "runjs"
cask "stats"
cask "switchhosts"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
cask "zed"
cask "zoom"
cask "zulu@17"

# ===== Optional: Additional Apps =====
# Uncomment to install these apps
# cask "1password"
# cask "adguard"
# cask "alt-tab"
# cask "claude"
# cask "cyberduck"
# cask "google-chrome"
# cask "jetbrains-toolbox"
# cask "obsidian"
# cask "popclip"
# cask "postman"
# cask "raycast"
# cask "rectangle-pro"
# cask "slack"
# cask "spotify"
# cask "warp"

# ===== Fonts =====
cask "font-d2coding"
cask "font-hack"
cask "font-jetbrains-mono"
cask "font-psudofont-liga-mono"
cask "font-sarasa-gothic"
